packages:
  - packages/*
  - apps/*

# Define a catalog of version ranges.
catalog:
  typegpu: https://pkg.pr.new/software-mansion/TypeGPU/typegpu@e598b31a3d03476d47bd66002e80dfacb54d8203
  unplugin-typegpu: ^0.2.2
